source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'bootstrap-on-rails'
gem 'less-rails'
gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'thin'
gem 'debugger', group: [:development, :test]

gem 'typhoeus', '~> 0.6.5'
gem 'virtus', '~> 1.0.0'
gem 'addressable', '~> 2.3.5'
gem 'hashie'
